# Generated by Django 2.2.19 on 2023-01-03 09:32

import django.core.validators
from django.db import migrations, models
import utils.strings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=utils.strings.LowerCaseEmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте буквы, цифры, знаки ., @, +, -', regex='^[\\w.@+-]+$')], verbose_name='Nickname пользователя'),
        ),
    ]
