# Generated by Django 2.2.19 on 2022-12-29 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
