# Generated by Django 2.2.19 on 2023-01-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribe_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
