# Generated by Django 2.2.19 on 2023-01-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe_to_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='not_banned',
        ),
    ]
