# Generated by Django 2.2.19 on 2023-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_no_custom_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
