version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:    
    image: chuvashevalena/foodgram_frontend:latest
    pull_policy: always
    volumes:
      - ../frontend/:/app/result_build/

  backend:    
    image: chuvashevalena/foodgram_backend:latest
    restart: always
    pull_policy: always
    volumes:
      - media_backend_value:/app/media/
      - static_backend_value:/app/static/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_backend_value:/var/html/media/
      - static_backend_value:/var/html/static/
    depends_on:
      - frontend
      - backend
volumes:
  db_value:
  static_backend_value:
  media_backend_value:
