# Generated by Django 2.2.19 on 2023-01-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
