# Generated by Django 2.2.19 on 2023-01-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('author__id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
